services:
  mongo:
    container_name: mongo-container
    image: mongo:latest
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  api:
    container_name: api-container
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/casados-para-sempre
    restart: always
    environment:
      - HUSKY_SKIP_INSTALL=1
      - MONGO_URL=mongodb://mongo:27017/casados-para-sempre
    volumes:
      - ./dist/:/usr/src/clean-node-api/dist/
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo
